services:
  wiki:
    image: squidfunk/mkdocs-material:latest
    container_name: novabot-wiki
    ports:
      - "8100:8000"
    volumes:
      - .:/docs
    stdin_open: true
    tty: true
    restart: unless-stopped
