; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	h2zero/NimBLE-Arduino@^2.1.1
	SD
	SPI
	DNSServer
	terrorsl/sMQTTBroker@^0.1.8
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
	-DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=3

[env:waveshare_lcd2]
platform = espressif32 @ 6.4.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	h2zero/NimBLE-Arduino@^2.1.1
	SD
	SPI
	lvgl/lvgl@^8.4.0
	moononournation/GFX Library for Arduino@1.5.0
	terrorsl/sMQTTBroker@^0.1.8
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
	-DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
	-DLV_CONF_INCLUDE_SIMPLE
	-Isrc
	-DLCD_MOSI=38
	-DLCD_MISO=40
	-DLCD_SCLK=39
	-DLCD_CS=45
	-DLCD_DC=42
	-DLCD_RST=-1
	-DLCD_BL=1
	-DTOUCH_SDA=48
	-DTOUCH_SCL=47
	-DTOUCH_INT=-1
	-DTOUCH_RST=-1
	-DSD_CS=41
	-DWAVESHARE_LCD

[env:jc3248w535]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	h2zero/NimBLE-Arduino@^2.1.1
	SD_MMC
	lvgl/lvgl@^8.4.0
	terrorsl/sMQTTBroker@^0.1.8
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
	-DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
	-DLV_CONF_INCLUDE_SIMPLE
	-Isrc
	; JC3248W535 pin definitions
	-DJC3248W535
	-DLCD_CS=45
	-DLCD_SCK=47
	-DLCD_SDA0=21
	-DLCD_SDA1=48
	-DLCD_SDA2=40
	-DLCD_SDA3=39
	-DLCD_TE=38
	-DLCD_RST=-1
	-DLCD_BL=1
	-DTOUCH_SDA=4
	-DTOUCH_SCL=8
	-DTOUCH_INT=3
	-DTOUCH_RST=-1
	-DSD_MMC_D0=13
	-DSD_MMC_CLK=12
	-DSD_MMC_CMD=11
	-DAUDIO_BCK=42
	-DAUDIO_LRCK=2
	-DAUDIO_DO=41
	-DBAT_ADC=5

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_deps =
	h2zero/NimBLE-Arduino@^2.1.1
	SD
	SPI
	DNSServer
	WebServer
	terrorsl/sMQTTBroker@^0.1.8
build_flags = 
	-DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
	-DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
